import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'theme/app_theme.dart';
import 'screens/main_screen.dart';
import 'services/business_repository.dart';
import 'services/mock_business_repository.dart';
import 'services/firestore_business_repository.dart';
import 'services/ai_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  BusinessRepository repository;
  try {
    // Attempt to initialize Firebase
    // In a real app, you'd have the firebase_options.dart generated by flutterfire CLI
    await Firebase.initializeApp();
    repository = FirestoreBusinessRepository();
  } catch (e) {
    // Fallback to mock for local development or if Firebase is not yet set up
    print('Firebase initialization failed: $e. Falling back to MockRepository.');
    repository = MockBusinessRepository();
  }

  // Initialize AI Service with a placeholder key for now
  final aiService = AiService(apiKey: const String.fromEnvironment('GEMINI_API_KEY', defaultValue: ''));

  runApp(RuleOneApp(repository: repository, aiService: aiService));
}

class RuleOneApp extends StatelessWidget {
  final BusinessRepository repository;
  final AiService aiService;

  const RuleOneApp({
    super.key,
    required this.repository,
    required this.aiService,
  });

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Rule No. 1',
      debugShowCheckedModeBanner: false,
      themeMode: ThemeMode.dark,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      home: MainScreen(repository: repository, aiService: aiService),
    );
  }
}
